# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import fxgb_pb2 as fxgb__pb2


class FXGBWorkerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartJob = channel.unary_unary(
        '/FXGBWorker/StartJob',
        request_serializer=fxgb__pb2.Job.SerializeToString,
        response_deserializer=fxgb__pb2.WorkerResponse.FromString,
        )


class FXGBWorkerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FXGBWorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartJob': grpc.unary_unary_rpc_method_handler(
          servicer.StartJob,
          request_deserializer=fxgb__pb2.Job.FromString,
          response_serializer=fxgb__pb2.WorkerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FXGBWorker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
