# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fxgb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fxgb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nfxgb.proto\"\xc3\x01\n\x03Job\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x15\n\x03\x65nv\x18\x02 \x01(\x0b\x32\x08.Job.Env\x1a\x97\x01\n\x03\x45nv\x12\x18\n\x10\x44MLC_TRACKER_URI\x18\x01 \x01(\t\x12\x19\n\x11\x44MLC_TRACKER_PORT\x18\x02 \x01(\x05\x12\x11\n\tDMLC_ROLE\x18\x03 \x01(\t\x12\x16\n\x0e\x44MLC_NODE_HOST\x18\x04 \x01(\t\x12\x17\n\x0f\x44MLC_NUM_WORKER\x18\x05 \x01(\x05\x12\x17\n\x0f\x44MLC_NUM_SERVER\x18\x06 \x01(\x05\"&\n\x0eWorkerResponse\x12\x14\n\x0c\x61\x63\x63\x65pted_job\x18\x01 \x01(\x08\x32\x31\n\nFXGBWorker\x12#\n\x08StartJob\x12\x04.Job\x1a\x0f.WorkerResponse\"\x00\x62\x06proto3')
)




_JOB_ENV = _descriptor.Descriptor(
  name='Env',
  full_name='Job.Env',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DMLC_TRACKER_URI', full_name='Job.Env.DMLC_TRACKER_URI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DMLC_TRACKER_PORT', full_name='Job.Env.DMLC_TRACKER_PORT', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DMLC_ROLE', full_name='Job.Env.DMLC_ROLE', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DMLC_NODE_HOST', full_name='Job.Env.DMLC_NODE_HOST', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DMLC_NUM_WORKER', full_name='Job.Env.DMLC_NUM_WORKER', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DMLC_NUM_SERVER', full_name='Job.Env.DMLC_NUM_SERVER', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=210,
)

_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='Job.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env', full_name='Job.env', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JOB_ENV, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=210,
)


_WORKERRESPONSE = _descriptor.Descriptor(
  name='WorkerResponse',
  full_name='WorkerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accepted_job', full_name='WorkerResponse.accepted_job', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=250,
)

_JOB_ENV.containing_type = _JOB
_JOB.fields_by_name['env'].message_type = _JOB_ENV
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['WorkerResponse'] = _WORKERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {

  'Env' : _reflection.GeneratedProtocolMessageType('Env', (_message.Message,), {
    'DESCRIPTOR' : _JOB_ENV,
    '__module__' : 'fxgb_pb2'
    # @@protoc_insertion_point(class_scope:Job.Env)
    })
  ,
  'DESCRIPTOR' : _JOB,
  '__module__' : 'fxgb_pb2'
  # @@protoc_insertion_point(class_scope:Job)
  })
_sym_db.RegisterMessage(Job)
_sym_db.RegisterMessage(Job.Env)

WorkerResponse = _reflection.GeneratedProtocolMessageType('WorkerResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORKERRESPONSE,
  '__module__' : 'fxgb_pb2'
  # @@protoc_insertion_point(class_scope:WorkerResponse)
  })
_sym_db.RegisterMessage(WorkerResponse)



_FXGBWORKER = _descriptor.ServiceDescriptor(
  name='FXGBWorker',
  full_name='FXGBWorker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=252,
  serialized_end=301,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartJob',
    full_name='FXGBWorker.StartJob',
    index=0,
    containing_service=None,
    input_type=_JOB,
    output_type=_WORKERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FXGBWORKER)

DESCRIPTOR.services_by_name['FXGBWorker'] = _FXGBWORKER

# @@protoc_insertion_point(module_scope)
